### ISSUE TITLE
Allow conversion between logical and scalars

### ISSUE THREAD

**Issue by PaulGannay** [agenium-scale/nsimd#14]
It can easily be done using if_else, but we should offer a simpler way of doing it.

**Comment by gquintin** [comment]
Two operators have been added in commit 6eb18d8a63f5125e9077332622f64f1d33948926:

- `to_mask` takes a vector of logicals and produces a mask (all zeros or all ones) in the given type even for `float` and `double`.
- `to_logical` takes a vector and produce a vector of logicals. Each zero element (in the sense all bits set to zero) is converted to false and true otherwise.

What could be missing is more functions for converting vectors of logicals to vectors, for example:

- `to_one_zero` could convert true's to one's and false's to zero's
- `to_minus_one_zero` could convert true's to minus one's and false's to zero's

Many other can/may be useful. As for now we do not have the need for such operators I am closing the issue. If the need arises in the future then we will reopen this issue.
