### ISSUE TITLE
Autodetect CPU architecture

### ISSUE THREAD

**Issue by eschnett** [agenium-scale/nsimd#26]
It seems that I need to add `-DNSIMD_AVX2 -DNSIMD_FMA` when I compile.

Instead, nsimd should be able to detect this from CPU flags at compile time, or should remember this from how it was configured with cmake.

**Comment by gquintin** [comment]
Yes you need to specify explicitly what SIMD extension you want for compiling.

We do not detect automatically the SIMD extension specified by the user in its compilation command because some compilers do not offer this feature. For example cf. <https://www.boost.org/doc/libs/1_71_0/doc/html/predef/reference.html> and <https://msdn.microsoft.com/en-us/library/b0084kay.aspx>. Thus a "manual" system is always necessary.

Another reason is that autodetecting the SIMD extension is compiler/compiler version/cpu/system dependant which means a lot of code for a (most likely buggy) feature which can be an inconvenience sometimes: when testing/benchmarking some programs that depends on NSIMD on which we do not control compile flags, it is really convenient to be able to specify *simply* what we want to do.

But we can improve this current NSIMD system. For example, if I am not mistaken there is no Intel CPU with AVX and without FMA (at least they are not easily found.) Therefore `-DAVX` could imply `-DFMA`.
