### ISSUE TITLE
Calculate i32 horizontal sum in nsimd.

### ISSUE THREAD

**Issue by luoming17** [agenium-scale/nsimd#97]
Hi, I found nsimd::addv function only support f64, f32 and f16, but I have a nsimd::pack<int32_t> type SimdVector and I want calculate it's horizontal sum, I try to reinterpret to f32 but the result isn't correct.

Will the nsimd::addv function support interger value type in the future? 
Is there any way to calculate i32 horizontal sum in nsimd?

**Comment by luoming17** [comment]
By the way, is there any way to explicit specify which register I want to use in an nsimd::pack?
I means I compile my project with

```add_compile_options(-DAVX512_SKYLAKE -DFMA -march=skylake-avx512)```

And I have two function. In function A, I want use 512-bits registers, but in function B, I want use 128-bits registers.

**Comment by gquintin** [comment]
Hi @luoming17 

## Horizontal sum

Indeed the `addv` operator doe snot support integers yet. The reason is that there is two "ways" to do it:
- saturated horizontal sum
- standard C horizontal sum (with possible overflows/underflows)

Since then we have decided what to do but did not manage to find time to actually implement it:

- The `addv` operator will perform standard C horizontal sum.
- A new `addvs` operator will perform saturated horizontal sum.

If you already have implementations, we would really appreciate to include them. You see [the documentation on how to add a new operator](https://agenium-scale.github.io/nsimd/contribute.html) if you wish.

## Use 128-bits registers when compiling for AVX-512

You can of course use 128-bits registers when compiling for AVX/AVX2 or AVX-512:

```c++
#include <nsimd/nsimd-all.hpp>

void foo() {
    // Native SIMD register:
    // - __m128 when targeting SSE
    // - __m256 when targeting AVX
    // - __m512 when targeting AVX-512
    nsimd::pack<float> a;

    // __m128 whatever the target is
    nsimd::pack<float, 1, nsimd::sse42> b;
}
```

Let me however warn you about this. This will make you code non portable. I do not know your use case but maybe what follows will apply to you:

```c++
#if defined(NSIMD_X86)
  typedef nsimd::pack<float> pack_t;
  typedef nsimd::pack<float, 1, nsimd::sse2> pack128_t;
#if defined(NSIMD_ARM)
  #if NSIMD_WORD_SIZE == 32
    typedef nsimd::pack<float> pack_t;
    typedef nsimd::pack<float, 1, nsimd::neon128> pack128_t;
  #else
    typedef nsimd::pack<float> pack_t;
    typedef nsimd::pack<float, 1, nsimd::aarch64> pack128_t;
  #endif
#else
  #error "Unsupported architecture"
#endif
```

This is not the first time we see this kind of demand. When we worked on GROMACS we add to write something like the above because GROMACS needs a 128-bits SIMD type. Maybe we should think of adding this into NSIMD. I have not though about this so I do not know if it is wise or not.

**Comment by luoming17** [comment]
Thank you, I have solved my problem.
